spring:
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web

lotto:
  number-generator:
    facade:
      count: 6
      lowerBound: 1
      upperBound: 99
    http:
      client:
        config:
          uri: http://www.randomnumberapi.com
          port: 80
          connectionTimeout: 5000
          readTimeout: 5000
    lotteryRunOccurrence: "0 0 12 * * 6"
